title:            "JACK DAIRY"
description:      "用来记录未来一年的心得"
disqus_shortname: "jkcrazy"
#Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              "http://0.0.0.0:4000"
url:              "http://dairy.jkcrazy.net"

# Owner/author information
owner:
  name:           "Jack Sun (孙伟)"
  avatar:         avatar.jpg
  bio:            "一个上海交大挨踢男，非典型极客，珍视时光中的每一刻，用心体会并记录身旁悄然流逝的点点滴滴"
  email:          jacksunwei@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:         jacksunwei
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+JackSunCrazy

# Background image to be tiled on all pages
background: ps_neutral.png

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-42599176-6"
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Jack Sun
    url: http://www.jkcrazy.net
    external: true
  - title: Tech Blog
    url: http://blog.jkcrazy.net
    external: true
  - title: Life Blog
    url: http://life.jkcrazy.net
    external: true
    

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:title

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

